// DIFFERENT TYPES OF FUNCTION IN JS :-

// 1. REGULAR FUNCTION
// 2. ARROW FUNCTION
// 3. ANONYMOUS FUNCTION
// 4. FUNCTION EXPRESSION
// 5. CALLBACK FUNCTION
// 6. FIRST-CLASS FUNCTION
// 7. HIGHER-ORDER FUNCTION
// 8. SELF-INVOKING FUNCTION (IIFE)
